application:
  name: prod环境 @artifactId@
  version: prod环境 @version@


developer:
  name: prod环境 zdz
  website: prod环境
  web-site: prod环境
  webSite: prod环境
  WEBSITE: prod环境

  qq: prod环境 252012798
  phone-number: prod环境x